[workspace]
members = [
    "visi-core",
    "visi",
]
resolver = "2"

[workspace.package]
version = "0.1.2"
rust-version = "1.88"
homepage = "https://github.com/albert-yu/visi"
repository = "https://github.com/albert-yu/visi"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
