[package]
name = "libvisi"
version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"
description.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
calamine = "0.36"
cfb = "0.14"
getrandom = { version = "0.2", features = ["js"] }
glam = "0.29"
libm = "0.2"
log = "0.4"
quick-xml = "0.36"
rand = "0.8"
regex = "1"
rust_xlsxwriter = "0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web-time = "1.1"
zip = { version = "2.1", default-features = false, features = ["deflate"] }

[dev-dependencies]
proptest = "1"
